process.env.NODE_ENV = 'test';

module.exports = {
  token: null,
  festivalId: null,
  festivalPlaceId: null,
  festivalPlaceIdParent: null,
  festivalCategoryId: null,
  festivalCategoryIdParent: null,
  festivalEventId: null,
  newsId: null,
  festivalNewsId: null
};

before(function (done) {

  module.exports.token = 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImxlZ2FjeS10b2tlbi1rZXkiLCJ0eXAiOiJKV1QifQ.eyJqdGkiOiJkN2U1YWIyOWJhMmY0OGNjOTU2MWY5ODZkNTA3MmEzZiIsInN1YiI6ImQ2MDgzNWY1LTYzNTEtNDdmNy1hNGNmLTE4ZjM5ODdjZjNhNSIsInNjb3BlIjpbImZlc3RpdmFsczpjcmVhdGUiLCJuZXdzOmNyZWF0ZSIsImNhdGVnb3JpZXM6ZGVsZXRlIiwiYWRtaW4iLCJwbGFjZXM6Z2V0IiwibmV3czp1cGRhdGUiLCJjYXRlZ29yaWVzOnVwZGF0ZSIsInBsYWNlczpkZWxldGUiLCJmZXN0aXZhbHM6dXBkYXRlIiwicGxhY2VzOnVwZGF0ZSIsImNhdGVnb3JpZXM6Y3JlYXRlIiwiZXZlbnRzOmdldCIsImNhdGVnb3JpZXM6Z2V0IiwicGxhY2VzOmNyZWF0ZSIsIm9wZW5pZCIsImV2ZW50czpjcmVhdGUiLCJmZXN0aXZhbHM6ZGVsZXRlIiwiZmVzdGl2YWxzOmdldCIsIm5ld3M6ZGVsZXRlIiwibmV3czpnZXQiLCJldmVudHM6dXBkYXRlIiwiZXZlbnRzOmRlbGV0ZSJdLCJjbGllbnRfaWQiOiJmZXN0aXZhbHMtYWRtaW4iLCJjaWQiOiJmZXN0aXZhbHMtYWRtaW4iLCJhenAiOiJmZXN0aXZhbHMtYWRtaW4iLCJncmFudF90eXBlIjoicGFzc3dvcmQiLCJ1c2VyX2lkIjoiZDYwODM1ZjUtNjM1MS00N2Y3LWE0Y2YtMThmMzk4N2NmM2E1Iiwib3JpZ2luIjoidWFhIiwidXNlcl9uYW1lIjoicHlya29uIiwiZW1haWwiOiJqYWNlay53b2RhQHB5cmtvbi5wbCIsImF1dGhfdGltZSI6MTQ5MDk5NjA4NiwicmV2X3NpZyI6ImVlMmI0NDQ4IiwiaWF0IjoxNDkwOTk2MDg2LCJleHAiOjE0OTEwMzkyODYsImlzcyI6Imh0dHBzOi8vZmVzdGl2YWxzLnRlY2gvb2F1dGgvdG9rZW4iLCJ6aWQiOiJ1YWEiLCJhdWQiOlsiZmVzdGl2YWxzLWFkbWluIiwib3BlbmlkIl19.Wvwh1Mf8OeS1LvnKypg5WqK2bYeFf2-DhQDT9SrQf8Z7cHSCaDzHAoKBL0CF0GQQnRN92DT0V0fdfPvMevE9QtkWMsv9nPCRBZXefrndsuRjp1-6hfLieM4Uet3b6dJ2N1paVI0hrbNgUB3WhkdvH_rhadw5n5HcMcBb9omnjihtyoBliw8Ei91N9-FRQtl1GpcwPGgOqlw4OdVHc4QlxqOhPujtc8vzPd2mOMF9jFzvoeVYal2DtQyxWZumaSGzE8_oFEAywJzHfHb4y1AIaVabAeEuSRnXSbKS7YshaRpmZxHwEvtiTdD1xEmq9Tp1fpxqCE7xccIQQWwk8rKTSQ';

  console.log('Starting server for functional tests ..');
  var app = require('../lib/app');

  app.startServer(function (err, port) {
    console.log('Starting server on port %d ..[done]', port);

    setTimeout(done, 1000);

  });
});